export const MSG = {
  PING: "PING",
  PONG: "PONG",
  GET_EXTENSION_STATUS: "GET_EXTENSION_STATUS",
  EXTENSION_STATUS: "EXTENSION_STATUS",
  OPEN_SIDE_PANEL: "OPEN_SIDE_PANEL",
  SIDE_PANEL_OPENED: "SIDE_PANEL_OPENED",
  HEARTBEAT: "HEARTBEAT",
} as const;
